version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  groups:
    minor-patch-dependencies:
      update-types: ["minor", "patch"]
