[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
aiohttp = "^3.8.1"
toml = "^0.10.2"
dockerflow = "^2022.1.0"
async-timeout = "^4.0.2"
sentry-sdk = "^1.5.7"
termcolor = "^1.1.0"
aiohttp_cors = "^0.7.0"
backoff = "^1.11.1"
python-decouple = "^3.6"
logging-color-formatter = "^1.0.2"
google-cloud-bigquery = "^2.34.2"
# Extra dependencies for checks.
kinto-http = { version = "^10.8.0", optional = true }
cryptography = { version = "^36.0.1", optional = true }
websockets = { version = "^10.2", optional = true }
requests = { version = "^2.26.0", optional = true }
beautifulsoup4 = { version = "^4.10.0", optional = true }
autograph-utils = { version = "^0.1.1", optional = true }
canonicaljson-rs = { version = "^0.4.0", optional = true }
taskcluster = { version = "^44.8.3", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
aioresponses = "^0.7.3"
pytest-aiohttp = "^1.0.4"
black = "^22.3"
flake8 = "^4.0.1"
mypy = "^0.940"
pytest-cov = "^3.0.0"
isort = "^5.10.1"
bandit = "^1.7.4"
responses = "^0.19.0"
types-toml = "^0.10.4"
types-requests = "^2.27.16"
types-termcolor = "^1.1.3"

[tool.poetry.extras]
remotesettings = [
    "kinto-http",
    "cryptography",
    "websockets",
    "requests",
    "beautifulsoup4",
    "autograph-utils",
    "canonicaljson-rs",
]
taskcluster = [
    "taskcluster",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
