[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aiohttp = "^3.9.1"
toml = "^0.10.2"
dockerflow = "^2022.8.0"
async-timeout = "^4.0.3"
sentry-sdk = "^1.39.2"
termcolor = "^2.4.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.8"
logging-color-formatter = "^1.0.3"
google-cloud-bigquery = "^3.14.1"
detect-secrets = "^1.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
aioresponses = "^0.7.6"
pytest-aiohttp = "^1.0.5"
black = "^23.12"
flake8 = "^7.0.0"
mypy = "^1.8"
pytest-cov = "^4.1.0"
isort = "^5.13.2"
bandit = "^1.7.7"
responses = "^0.24.1"
types-toml = "^0.10.8"
types-requests = "^2.31.0"
types-termcolor = "^1.1.6"

[tool.poetry.group.remotesettings]
optional = true

[tool.poetry.group.taskcluster]
optional = true

[tool.poetry.group.remotesettings.dependencies]
kinto-http = "^11.0.1"
cryptography = "^42.0.1"
websockets = "^12.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.3"
autograph-utils = "^0.1.1"
canonicaljson-rs = "^0.5.0"

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^60.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
