[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aiohttp = "^3.8.4"
toml = "^0.10.2"
dockerflow = "^2022.8.0"
async-timeout = "^4.0.2"
sentry-sdk = "^1.18.0"
termcolor = "^2.2.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.8"
logging-color-formatter = "^1.0.3"
google-cloud-bigquery = "^3.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
aioresponses = "^0.7.4"
pytest-aiohttp = "^1.0.4"
black = "^22.10"
flake8 = "^6.0.0"
mypy = "^1.1"
pytest-cov = "^4.0.0"
isort = "^5.12.0"
bandit = "^1.7.5"
responses = "^0.23.1"
types-toml = "^0.10.8"
types-requests = "^2.28.11"
types-termcolor = "^1.1.6"

[tool.poetry.group.remotesettings]
optional = true

[tool.poetry.group.taskcluster]
optional = true

[tool.poetry.group.remotesettings.dependencies]
kinto-http = "^11.0.0"
cryptography = "^40.0.1"
websockets = "^10.4"
requests = "^2.28.2"
beautifulsoup4 = "^4.12.0"
autograph-utils = "^0.1.1"
canonicaljson-rs = "^0.5.0"

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^44.23.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
