[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
aiohttp = "^3.8.3"
toml = "^0.10.2"
dockerflow = "^2022.8.0"
async-timeout = "^4.0.2"
sentry-sdk = "^1.10.1"
termcolor = "^2.1.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.6"
logging-color-formatter = "^1.0.3"
google-cloud-bigquery = "^3.3.5"
# Extra dependencies for checks.
kinto-http = { version = "^11.0.0", optional = true }
cryptography = { version = "^38.0.1", optional = true }
websockets = { version = "^10.4", optional = true }
requests = { version = "^2.28.1", optional = true }
beautifulsoup4 = { version = "^4.11.1", optional = true }
autograph-utils = { version = "^0.1.1", optional = true }
canonicaljson-rs = { version = "^0.4.0", optional = true }
taskcluster = { version = "^44.22.1", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
aioresponses = "^0.7.3"
pytest-aiohttp = "^1.0.4"
black = "^22.10"
flake8 = "^5.0.4"
mypy = "^0.982"
pytest-cov = "^4.0.0"
isort = "^5.10.1"
bandit = "^1.7.4"
responses = "^0.22.0"
types-toml = "^0.10.8"
types-requests = "^2.28.11"
types-termcolor = "^1.1.6"

[tool.poetry.extras]
remotesettings = [
    "kinto-http",
    "cryptography",
    "websockets",
    "requests",
    "beautifulsoup4",
    "autograph-utils",
    "canonicaljson-rs",
]
taskcluster = [
    "taskcluster",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
