[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aiohttp = "^3.10.5"
toml = "^0.10.2"
dockerflow = "^2024.4.2"
async-timeout = "^4.0.3"
sentry-sdk = "^2.13.0"
termcolor = "^2.4.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.8"
logging-color-formatter = "^1.1.0"
google-cloud-bigquery = "^3.25.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
aioresponses = "^0.7.6"
pytest-aiohttp = "^1.0.5"
mypy = "^1.11"
pytest-cov = "^5.0.0"
bandit = "^1.7.9"
responses = "^0.25.3"
types-toml = "^0.10.8"
types-requests = "^2.32.0"
types-termcolor = "^1.1.6"
ruff = "^0.6.3"
detect-secrets = "^1.5.0"

[tool.poetry.group.remotesettings]
optional = true

[tool.poetry.group.taskcluster]
optional = true

[tool.poetry.group.remotesettings.dependencies]
kinto-http = "^11.2.0"
cryptography = "^43.0.0"
websockets = "^13.0"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
autograph-utils = "^0.3.0"
canonicaljson-rs = "^0.6.0"

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^68.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
extend-exclude = [
    "__pycache__",
    ".venv/",
    "kinto/plugins/admin/node_modules/",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # flake8
    "F",
    # isort
    "I",
]
ignore = [
    # `format` will wrap lines.
    "E501",
]

[tool.ruff.lint.isort]
lines-after-imports = 2
