[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8.5"
aiohttp = "^3.7.4"
toml = "^0.10.2"
dockerflow = "^2021.7.0"
async-timeout = "^3.0.1"
sentry-sdk = "^1.5.4"
termcolor = "^1.1.0"
aiohttp_cors = "^0.7.0"
backoff = "^1.11.1"
python-decouple = "^3.5"
logging-color-formatter = "^1.0.2"
google-cloud-bigquery = "^2.32.0"
# Extra dependencies for checks.
kinto-http = { version = "^10.8.0", optional = true }
cryptography = { version = "^36.0.1", optional = true }
websockets = { version = "^10.1", optional = true }
requests = { version = "^2.26.0", optional = true }
beautifulsoup4 = { version = "^4.10.0", optional = true }
autograph-utils = { version = "^0.1.1", optional = true }
canonicaljson-rs = { version = "^0.3.0", optional = true }
taskcluster = { version = "^44.4.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
aioresponses = "^0.7.3"
pytest-aiohttp = "^0.3.0"
black = "^21.12b0"
flake8 = "^4.0.1"
mypy = "^0.931"
pytest-cov = "^3.0.0"
isort = "^5.10.1"
bandit = "^1.7.1"
responses = "^0.17.0"
types-toml = "^0.10.3"
types-requests = "^2.27.7"
types-termcolor = "^1.1.3"

[tool.poetry.extras]
remotesettings = [
    "kinto-http",
    "cryptography",
    "websockets",
    "requests",
    "beautifulsoup4",
    "autograph-utils",
    "canonicaljson-rs",
]
taskcluster = [
    "taskcluster",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
