[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
aiohttp = "^3.8.5"
toml = "^0.10.2"
dockerflow = "^2022.8.0"
async-timeout = "^4.0.3"
sentry-sdk = "^1.31.0"
termcolor = "^2.3.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.8"
logging-color-formatter = "^1.0.3"
google-cloud-bigquery = "^3.11.4"
detect-secrets = "^1.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
aioresponses = "^0.7.4"
pytest-aiohttp = "^1.0.5"
black = "^23.9"
flake8 = "^6.1.0"
mypy = "^1.5"
pytest-cov = "^4.1.0"
isort = "^5.12.0"
bandit = "^1.7.5"
responses = "^0.23.3"
types-toml = "^0.10.8"
types-requests = "^2.31.0"
types-termcolor = "^1.1.6"

[tool.poetry.group.remotesettings]
optional = true

[tool.poetry.group.taskcluster]
optional = true

[tool.poetry.group.remotesettings.dependencies]
kinto-http = "^11.0.1"
cryptography = "^41.0.4"
websockets = "^11.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
autograph-utils = "^0.1.1"
canonicaljson-rs = "^0.5.0"

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^55.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
