[tool.poetry]
name = "telescope"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
aiohttp = "^3.8.3"
toml = "^0.10.2"
dockerflow = "^2022.8.0"
async-timeout = "^4.0.2"
sentry-sdk = "^1.12.1"
termcolor = "^2.2.0"
aiohttp_cors = "^0.7.0"
backoff = "^2.2.1"
python-decouple = "^3.6"
logging-color-formatter = "^1.0.3"
google-cloud-bigquery = "^3.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
aioresponses = "^0.7.3"
pytest-aiohttp = "^1.0.4"
black = "^22.10"
flake8 = "^6.0.0"
mypy = "^0.991"
pytest-cov = "^4.0.0"
isort = "^5.10.1"
bandit = "^1.7.4"
responses = "^0.22.0"
types-toml = "^0.10.8"
types-requests = "^2.28.11"
types-termcolor = "^1.1.6"

[tool.poetry.group.remotesettings]
optional = true

[tool.poetry.group.taskcluster]
optional = true

[tool.poetry.group.remotesettings.dependencies]
kinto-http = "^11.0.0"
cryptography = "^38.0.4"
websockets = "^10.4"
requests = "^2.28.1"
beautifulsoup4 = "^4.11.1"
autograph-utils = "^0.1.1"
canonicaljson-rs = "^0.4.0"

[tool.poetry.group.taskcluster.dependencies]
taskcluster = "^44.23.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
