version: 2
jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Use latest poetry
          command: curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Code lint
          command: make lint

  python-tests:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Get curl with HTTP2 and HTTP3 support
          command: |
            wget https://github.com/stunnel/static-curl/releases/download/8.1.1/curl-static-amd64-8.1.1.tar.xz
            tar -xvf curl-*.tar.xz
            mv curl /home/circleci/.local/bin/curl

      - run:
          name: Use latest poetry
          command: curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Test
          command: make tests
          environment:
            CURL_BINARY_PATH: /home/circleci/.local/bin/curl

  docker-build-test-publish:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Create version.json
          command: |
            printf '{"name":"%s", "commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" | tee version.json

      - store_artifacts:
          path: version.json

      - run:
          name: Build deployment container image
          command: docker build -t app:build .

      - run:
          name: Test from Docker
          command: docker run -it --user root app:build test

      - run:
          name: Docker Heartbeat
          command: |
            docker run --detach --name telescope --env CONFIG_FILE=/app/tests/checks/remotesettings/config.toml app:build
            docker exec telescope curl --retry 10 --retry-delay 1 --retry-connrefused http://0.0.0.0:8000/checks | grep remotesettings

      - run:
          name: Push to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              bin/deploy-dockerhub.sh latest
            fi
            if [[ "${CIRCLE_BRANCH}" == feature* ]] || [[ "${CIRCLE_BRANCH}" == dockerpush* ]]; then
              bin/deploy-dockerhub.sh "$CIRCLE_BRANCH"
            fi
            if [ -n "${CIRCLE_TAG}" ]; then
              bin/deploy-dockerhub.sh "$CIRCLE_TAG"
            fi

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/

      - python-tests:
          requires:
            - lint
          filters:
            tags:
              only: /.*/

      - docker-build-test-publish:
          requires:
            - python-tests
          filters:
            tags:
              only: /.*/
